
#ifndef PROYECTO_FINAL_INCLUDE_GPUMATRIX_GPUMATRIX_H_
#define PROYECTO_FINAL_INCLUDE_GPUMATRIX_GPUMATRIX_H_

namespace GPUMatrix {
    
void HelloThreadIdx();

}  // namespace GPUMatrix

#endif  // PROYECTO_FINAL_INCLUDE_GPUMATRIX_GPUMATRIX_H_
